# Generated by Django 5.2.4 on 2026-01-01 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bağımlılık Türü',
                'verbose_name_plural': 'Bağımlılık Türleri',
            },
        ),
        migrations.CreateModel(
            name='ApproachMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Yaklaşım Yöntemi',
                'verbose_name_plural': 'Yaklaşım Yöntemleri',
            },
        ),
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Eğitim Düzeyi',
                'verbose_name_plural': 'Eğitim Düzeyleri',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Seans Türü',
                'verbose_name_plural': 'Seans Türleri',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı',
                'verbose_name_plural': 'Uzmanlık Alanları',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Hedef Grup',
                'verbose_name_plural': 'Hedef Gruplar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('country', models.CharField(default='TR', max_length=64)),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta adresi')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('expert', 'Uzman'), ('client', 'Danışan')], max_length=10, verbose_name='Rol')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('country', models.CharField(default='TR', max_length=64, verbose_name='Ülke')),
                ('national_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ulusal Kimlik Numarası')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer'), ('pn2s', 'Belirtmek İstemiyor')], max_length=10, null=True, verbose_name='Cinsiyet')),
                ('id_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik Numarası')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Kullanıcı Adı')),
                ('timezone', models.CharField(default='Europe/Istanbul', help_text='Kullanıcının varsayılan saat dilimi', max_length=64, verbose_name='Saat Dilimi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yönetici Profili',
                'verbose_name_plural': 'Yönetici Profilleri',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_goal', models.TextField(blank=True, null=True, verbose_name='Destek Hedefi')),
                ('received_service_before', models.BooleanField(default=False, verbose_name='Daha Önce Hizmet Aldı mı?')),
                ('onboarding_complete', models.BooleanField(default=False, verbose_name='Profilini Tamamladı mı?')),
                ('is_active_in_treatment', models.BooleanField(default=True, verbose_name='Tedavi Aktif mi?')),
                ('substances_used', models.ManyToManyField(blank=True, related_name='clients', to='accounts.addictiontype', verbose_name='Bağımlılık Türleri')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danışan Profili',
                'verbose_name_plural': 'Danışan Profilleri',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Acil durum iletişim kişisinin tam adı.', max_length=128)),
                ('phone_number', models.CharField(help_text='Acil durum iletişim kişisinin telefon numarası.', max_length=20)),
                ('relationship', models.CharField(blank=True, help_text='Danışanla olan akrabalık veya yakınlık derecesi (Örn: Eş, Anne, Kardeş, Vasi).', max_length=64, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Bu kişinin birincil (ilk aranacak) acil durum kişisi olup olmadığı.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(help_text='İlgili acil durum iletişiminin ait olduğu danışan profili.', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Acil Durum Kişisi',
                'verbose_name_plural': 'Acil Durum Kişileri',
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Hakkında')),
                ('approval_status', models.BooleanField(default=False, verbose_name='Onay Durumu')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Unvan')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deneyim Yılı')),
                ('license_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Lisans Numarası')),
                ('institution', models.CharField(blank=True, max_length=256, null=True, verbose_name='Kurum')),
                ('session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Seans Ücreti')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('appointment_duration', models.PositiveIntegerField(default=45, verbose_name='Seans Süresi (dk)')),
                ('free_first_session', models.BooleanField(default=False, verbose_name='İlk Seans Ücretsiz mi?')),
                ('video_intro_url', models.URLField(blank=True, null=True, verbose_name="Tanıtım Videosu URL'si")),
                ('availability_status', models.CharField(choices=[('available', 'Müsait'), ('active', 'Aktif'), ('busy', 'Meşgul'), ('away', 'Tatilde')], default='available', max_length=32, verbose_name='Müsaitlik Durumu')),
                ('rating_average', models.FloatField(default=0, verbose_name='Ortalama Puan')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Puan Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('approach_methods', models.ManyToManyField(blank=True, related_name='experts', to='accounts.approachmethod', verbose_name='Yaklaşım Yöntemleri')),
                ('degree_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.degreelevel', verbose_name='Eğitim Düzeyi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='experts', to='accounts.language', verbose_name='Diller')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.major', verbose_name='Bölüm')),
                ('services', models.ManyToManyField(blank=True, related_name='experts', to='accounts.service', verbose_name='Hizmetler')),
                ('session_types', models.ManyToManyField(blank=True, related_name='experts', to='accounts.sessiontype', verbose_name='Seans Türleri')),
                ('specializations', models.ManyToManyField(blank=True, related_name='experts', to='accounts.specialization', verbose_name='Uzmanlık Alanları')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='experts', to='accounts.targetgroup', verbose_name='Hedef Gruplar')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.university', verbose_name='Üniversite')),
            ],
            options={
                'verbose_name': 'Uzman Profili',
                'verbose_name_plural': 'Uzman Profilleri',
            },
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='accounts.expertprofile', verbose_name='Atanan Uzman'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('profile_photo', 'Profil Fotoğrafı'), ('degree', 'Diploma / Sertifika'), ('cv', 'Özgeçmiş'), ('consent_form', 'Onay Formu'), ('other', 'Diğer')], max_length=32)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Birincil mi?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'constraints': [models.CheckConstraint(condition=models.Q(('is_primary', False), ('is_current', True), _connector='OR'), name='primary_must_be_current')],
            },
        ),
    ]
