# Generated by Django 5.2.4 on 2026-08-22 12:48

from django.db import migrations, models


def backfill_status_from_verified(apps, schema_editor):
    """Yeni eklenen `status` alanı için var olan veriyi eski `verified`
    boolean'ından türet: bu özellik eklenmeden önce onaylanmış (verified=True)
    belgeler status='approved' olsun, geri kalanı varsayılan 'pending'de kalsın
    (geçmişte hiç 'reddedilmiş' kavramı yoktu, bu yüzden reddedilmiş olarak
    işaretlenecek bir kayıt yok - hepsi ya onaylı ya da bekliyor sayılır)."""
    Document = apps.get_model('accounts', 'Document')
    Document.objects.filter(verified=True).update(status='approved')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=16, verbose_name='Onay Durumu'),
        ),
        migrations.RunPython(backfill_status_from_verified, noop_reverse),
    ]
