# Generated by Django 5.2.4 on 2026-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
