# Generated by Django 5.2.4 on 2026-08-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_document_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='session_types',
        ),
    ]
