# Generated by Django 5.2.4 on 2026-08-28 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_expertprofile_session_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='recovery_status',
            field=models.CharField(blank=True, choices=[('in_recovery', 'İyileşme Sürecinde (Ex-User)'), ('active_treatment', 'Aktif Tedavide'), ('not_applicable', 'Uygulanamaz')], max_length=32, null=True, verbose_name='İyileşme Durumu'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='recovery_status_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğrulanma Tarihi'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='recovery_status_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_status_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Doğrulayan Admin'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('profile_photo', 'Profil Fotoğrafı'), ('degree', 'Diploma / Sertifika'), ('cv', 'Özgeçmiş'), ('consent_form', 'Onay Formu'), ('recovery_proof', 'İyileşme Durumu Belgesi'), ('other', 'Diğer')], max_length=32),
        ),
    ]
