# Generated by Django 5.2.4 on 2026-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=128, verbose_name='Ad')),
                ('category', models.CharField(choices=[('individual', 'Bireysel'), ('group', 'Grup'), ('educational', 'Eğitim')], max_length=16, verbose_name='Kategori')),
                ('requires_multi_participant', models.BooleanField(default=False, help_text='True ise bu seans türü GroupSession rezervasyon motorunu gerektirir.', verbose_name='Çok Katılımcılı mı?')),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Varsayılan Süre (dk)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seans Tipi',
                'verbose_name_plural': 'Seans Tipi Kataloğu',
                'ordering': ['name'],
            },
        ),
    ]
