# Generated by Django 5.2.4 on 2026-08-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOfferingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.SlugField(max_length=64, verbose_name='Varyant Anahtarı')),
                ('variant_label', models.CharField(max_length=128, verbose_name='Varyant Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.sessionoffering', verbose_name='Seans Tipi')),
            ],
            options={
                'verbose_name': 'Seans Tipi Varyantı',
                'verbose_name_plural': 'Seans Tipi Varyantları',
                'ordering': ['session_offering', 'variant_key'],
                'constraints': [models.UniqueConstraint(fields=('session_offering', 'variant_key'), name='unique_offering_variant_key')],
            },
        ),
    ]
