# Generated by Django 5.2.4 on 2026-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_related_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatması'), ('message', 'Yeni Not'), ('document_status', 'Belge Durumu')], max_length=30),
        ),
    ]
