# Generated by Django 5.2.4 on 2026-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatması'), ('message', 'Yeni Not'), ('document_status', 'Belge Durumu'), ('payment_required', 'Ödeme Gerekiyor'), ('payment_succeeded', 'Ödeme Alındı')], max_length=30),
        ),
    ]
