# Generated by Django 5.2.4 on 2026-08-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_groupsessionparticipant_reviewed_at_and_more'),
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.groupsession'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatması'), ('message', 'Yeni Not'), ('document_status', 'Belge Durumu'), ('payment_required', 'Ödeme Gerekiyor'), ('payment_succeeded', 'Ödeme Alındı'), ('free_trial_ready', 'Ücretsiz Seans Onayı Bekleniyor'), ('group_waitlist_spot_available', 'Grup Seansında Yer Açıldı'), ('group_join_requested', 'Grup Seansı Katılım Talebi'), ('group_payment_required', 'Grup Seansı İçin Ödeme Gerekiyor'), ('group_join_rejected', 'Grup Seansı Talebi Reddedildi')], max_length=30),
        ),
    ]
