# Generated by Django 5.2.4 on 2026-08-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_group_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatması'), ('message', 'Yeni Not'), ('document_status', 'Belge Durumu'), ('payment_required', 'Ödeme Gerekiyor'), ('payment_succeeded', 'Ödeme Alındı'), ('free_trial_ready', 'Ücretsiz Seans Onayı Bekleniyor'), ('group_waitlist_spot_available', 'Grup Seansında Yer Açıldı'), ('group_join_requested', 'Grup Seansı Katılım Talebi'), ('group_payment_required', 'Grup Seansı İçin Ödeme Gerekiyor'), ('group_join_rejected', 'Grup Seansı Talebi Reddedildi'), ('group_session_cancelled', 'Grup Seansı İptal Edildi'), ('group_participant_reassigned', 'Başka Bir Grup Seansına Aktarıldınız')], max_length=30),
        ),
    ]
