# Generated by Django 5.2.4 on 2026-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_reminder', 'Randevu Hatırlatması'), ('message', 'Yeni Not'), ('document_status', 'Belge Durumu'), ('payment_required', 'Ödeme Gerekiyor'), ('payment_succeeded', 'Ödeme Alındı'), ('free_trial_ready', 'Ücretsiz Seans Onayı Bekleniyor'), ('group_waitlist_spot_available', 'Grup Seansında Yer Açıldı'), ('group_join_requested', 'Grup Seansı Katılım Talebi'), ('group_payment_required', 'Grup Seansı İçin Ödeme Gerekiyor'), ('group_join_rejected', 'Grup Seansı Talebi Reddedildi'), ('group_session_cancelled', 'Grup Seansı İptal Edildi'), ('group_participant_reassigned', 'Başka Bir Grup Seansına Aktarıldınız'), ('appointment_requested', 'Yeni Randevu Talebi'), ('appointment_created', 'Randevu Oluşturuldu'), ('appointment_confirmed', 'Randevu Onaylandı'), ('appointment_cancel_requested', 'Randevu İptal Talebi'), ('appointment_cancelled', 'Randevu İptal Edildi'), ('form_submitted', 'Yeni Form Gönderimi')], max_length=30),
        ),
    ]
