# Generated by Django 5.2.4 on 2026-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_free_trial',
            field=models.BooleanField(default=False, verbose_name='Ücretsiz İlk Seans'),
        ),
    ]
