# Generated by Django 5.2.4 on 2026-08-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_expertprofile_session_types'),
        ('appointments', '0002_appointment_is_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.sessiontype', verbose_name='Seans Türü (Online/Yüz Yüze/Karma)'),
        ),
    ]
