# Generated by Django 5.2.4 on 2026-08-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_session_type'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='catalog.sessionoffering', verbose_name='Seans Tipi (Hizmet)'),
        ),
    ]
