# Generated by Django 5.2.4 on 2026-08-28 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientprofile_recovery_status_and_more'),
        ('appointments', '0005_backfill_session_offering'),
        ('catalog', '0002_sessionofferingvariant'),
        ('payments', '0005_pricingrule_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=90)),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='scheduled', max_length=16)),
                ('zoom_start_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions_as_expert', to=settings.AUTH_USER_MODEL)),
                ('session_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_sessions', to='catalog.sessionoffering', verbose_name='Seans Tipi')),
                ('session_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions', to='accounts.sessiontype', verbose_name='Seans Türü (Online/Yüz Yüze/Karma)')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions', to='catalog.sessionofferingvariant', verbose_name='Varyant (örn. Ex-User Grubu)')),
            ],
            options={
                'verbose_name': 'Grup Seansı',
                'verbose_name_plural': 'Grup Seansları',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_participations', to=settings.AUTH_USER_MODEL)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='appointments.groupsession')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_session_participation', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Grup Seansı Katılımcısı',
                'verbose_name_plural': 'Grup Seansı Katılımcıları',
                'constraints': [models.UniqueConstraint(fields=('group_session', 'client'), name='unique_group_session_participant')],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_waitlist_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='appointments.groupsession')),
            ],
            options={
                'verbose_name': 'Grup Seansı Bekleme Listesi Kaydı',
                'verbose_name_plural': 'Grup Seansı Bekleme Listesi Kayıtları',
                'ordering': ['joined_waitlist_at'],
                'constraints': [models.UniqueConstraint(fields=('group_session', 'client'), name='unique_group_session_waitlist_entry')],
            },
        ),
    ]
