# Generated by Django 5.2.4 on 2026-08-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_groupsession_groupsessionparticipant_and_more'),
        ('payments', '0006_alter_payment_payment_type_packagedefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsessionparticipant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İncelenme Tarihi'),
        ),
        migrations.AddField(
            model_name='groupsessionparticipant',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen Uzman'),
        ),
        migrations.AddField(
            model_name='groupsessionparticipant',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending_approval', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='groupsessionparticipant',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_session_participation', to='payments.payment'),
        ),
    ]
