# Generated by Django 5.2.4 on 2026-08-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_groupsessionparticipant_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsessionparticipant',
            name='original_group_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.groupsession', verbose_name='Orijinal Grup Seansı (Aktarım Öncesi)'),
        ),
    ]
