# Generated by Django 5.2.4 on 2026-08-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('single_session', 'Tekil Seans')], default='single_session', max_length=32, verbose_name='Ödeme Tipi')),
                ('flow', models.CharField(choices=[('direct', 'Direkt Satış'), ('preauth', 'Ön Provizyon')], default='direct', max_length=16, verbose_name='Akış')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('authorized', 'Bloke Kondu'), ('succeeded', 'Tahsil Edildi'), ('voided', 'Bloke Kaldırıldı'), ('failed', 'Başarısız'), ('refunded', 'İade Edildi')], default='pending', max_length=16, verbose_name='Durum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('conversation_id', models.CharField(max_length=64, unique=True, verbose_name='Conversation ID')),
                ('provider_token', models.CharField(blank=True, max_length=128, null=True, verbose_name='iyzico Token')),
                ('provider_payment_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='iyzico Payment ID')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='Hata Nedeni')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek Bilgi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment', verbose_name='Randevu')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Ödeyen')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
