# Generated by Django 5.2.4 on 2026-08-28 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_expertprofile_session_types'),
        ('catalog', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expert_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Uzman Kazancı'),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Platform Payı'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Danışan Fiyatı')),
                ('currency', models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi')),
                ('commission_type', models.CharField(choices=[('percentage', 'Yüzde'), ('fixed_amount', 'Sabit Tutar')], default='percentage', max_length=16, verbose_name='Komisyon Tipi')),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Komisyon Değeri')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('effective_until', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='accounts.expertprofile', verbose_name='Uzman')),
                ('session_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.sessionoffering', verbose_name='Seans Tipi')),
            ],
            options={
                'verbose_name': 'Fiyatlandırma Kuralı',
                'verbose_name_plural': 'Fiyatlandırma Kuralları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.pricingrule', verbose_name='Uygulanan Fiyatlandırma Kuralı'),
        ),
    ]
