# Generated by Django 5.2.4 on 2026-08-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('payments', '0003_backfill_pricing_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Kod')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Başlangıcı')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum Toplam Kullanım')),
                ('max_redemptions_per_user', models.PositiveIntegerField(default=1, verbose_name='Kullanıcı Başına Maksimum Kullanım')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İndirim Kodu',
                'verbose_name_plural': 'İndirim Kodları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'İndirim Kaynak Tipi',
                'verbose_name_plural': 'İndirim Kaynak Tipleri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.discountcode', verbose_name='Kullanılan İndirim Kodu'),
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Yüzde'), ('fixed_amount', 'Sabit Tutar')], default='percentage', max_length=16, verbose_name='İndirim Tipi')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Değer')),
                ('sponsor_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sponsor Adı')),
                ('cost_bearer', models.CharField(choices=[('platform', 'Platform'), ('expert', 'Uzman'), ('shared', 'Platform + Uzman (Paylaşımlı)')], default='platform', max_length=16, verbose_name='Maliyeti Kim Üstleniyor?')),
                ('expert_cost_share_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Sadece cost_bearer=SHARED iken kullanılır.', max_digits=5, null=True, verbose_name='Uzmanın Maliyet Payı (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_offering', models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm seans tiplerine uygulanır.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.sessionoffering', verbose_name='Uygulanacağı Seans Tipi')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='payments.discountsourcetype', verbose_name='Kaynak')),
            ],
            options={
                'verbose_name': 'İndirim Kuralı',
                'verbose_name_plural': 'İndirim Kuralları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='payments.discountrule', verbose_name='İndirim Kuralı'),
        ),
    ]
