# Generated by Django 5.2.4 on 2026-08-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sessionofferingvariant'),
        ('payments', '0004_discountcode_discountsourcetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Kıdem seviyesi/ex-user grubu gibi bir alt kırılıma özel fiyat gerekiyorsa doldurulur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.sessionofferingvariant', verbose_name='Varyant'),
        ),
    ]
