# Generated by Django 5.2.4 on 2026-08-28 08:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_groupsession_groupsessionparticipant_and_more'),
        ('catalog', '0002_sessionofferingvariant'),
        ('payments', '0005_pricingrule_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('single_session', 'Tekil Seans'), ('package', 'Seans Paketi')], default='single_session', max_length=32, verbose_name='Ödeme Tipi'),
        ),
        migrations.CreateModel(
            name='PackageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ad')),
                ('session_count', models.PositiveIntegerField(verbose_name='Seans Sayısı')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='İndirim Yüzdesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_definitions', to='catalog.sessionoffering', verbose_name='Seans Tipi')),
            ],
            options={
                'verbose_name': 'Paket Tanımı',
                'verbose_name_plural': 'Paket Tanımları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Danışan')),
                ('package_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.packagedefinition', verbose_name='Paket')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='package_purchase', to='payments.payment', verbose_name='Ödeme')),
            ],
            options={
                'verbose_name': 'Paket Satın Alımı',
                'verbose_name_plural': 'Paket Satın Alımları',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_usages', to='appointments.appointment')),
                ('group_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_usages', to='appointments.groupsession')),
                ('package_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.packagepurchase')),
            ],
            options={
                'verbose_name': 'Paket Kullanımı',
                'verbose_name_plural': 'Paket Kullanımları',
                'ordering': ['-used_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', False), ('group_session__isnull', True)), models.Q(('appointment__isnull', True), ('group_session__isnull', False)), _connector='OR'), name='package_usage_exactly_one_target')],
            },
        ),
    ]
