"""
Django settings for lunova_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import dj_database_url
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Env setup
env = environ.Env(
    DEBUG=(bool, False)
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

env_file = BASE_DIR / '.env'
if env_file.exists():
    env.read_env(env_file)

STORAGE_PROVIDER = env.str('STORAGE_PROVIDER', default='mock')
if STORAGE_PROVIDER == 'supabase':
    print(">>> Supabase etkinleştirildi.")
    SUPABASE_URL = env("SUPABASE_URL")
    SUPABASE_SERVICE_ROLE_KEY = env("SUPABASE_SERVICE_ROLE_KEY")
    SUPABASE_BUCKET = env("SUPABASE_BUCKET")
    
elif STORAGE_PROVIDER == 'mock':
    print(">>> MockStorage etkinleştirildi.")
    
else:
    raise ImproperlyConfigured(
        f"Invalid STORAGE_PROVIDER='{STORAGE_PROVIDER}'. "
        "Allowed values: 'supabase', 'mock'."
    )

# 1. Ortam Değişkenlerini Oku ve Temizle
# .strip() ile kenar boşluklarını, .title() ile harf hatalarını gideriyoruz (production -> Production)
ENV_NAME = env.str('ENVIRONMENT', default='Development').strip().title()
DB_URI = env.str('DB_URI', default='Lunova-lite').strip()

# 2. Veritabanı Seçimi ve Konfigürasyonu
if ENV_NAME == 'Production':
    # Production'da her zaman DB_URI üzerinden gidiyoruz
    DATABASES = {
        'default': dj_database_url.config(default=DB_URI)
    }
    
elif ENV_NAME == 'Development' and DB_URI == 'Lunova-lite':
    print(">>> Veritabanı: Lunova-lite (SQLite) kullanılıyor.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

elif ENV_NAME == 'Development' and DB_URI != 'Lunova-lite':
    # Slice hatasını önlemek için güvenli bir gösterim
    display_uri = DB_URI[:20] + "..." if len(DB_URI) > 20 else DB_URI
    print(f">>> Veritabanı: {display_uri} kullanılıyor.")
    
    DATABASES = {
        'default': dj_database_url.config(default=DB_URI)
    }
    
else:
    # Hem ENVIRONMENT yanlışsa hem de DB_URI uymuyorsa buraya düşer
    raise ImproperlyConfigured(
        f"Geçersiz Yapılandırma! ENVIRONMENT='{ENV_NAME}' veya DB_URI='{DB_URI}' hatalı. "
        "Lütfen ayarlarınızı kontrol edin."
    )

# STATIC_ROOT (production)
STATIC_ROOT = 'staticfiles'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# ALLOWED_HOSTS
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
if not ALLOWED_HOSTS:
    raise ImproperlyConfigured("No frontend URLs found for ALLOWED_HOSTS!")

# Application definition
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_extensions',

    # apps
    'accounts',         # Kullanıcılar
    'api',
    'zoom',             # Zoom
    'appointments',     # Randevular
    'forms',            # Formlar
    'rest_framework_simplejwt.token_blacklist',
    'availability',     # Müsaitlik
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # React ile haberleşmek için
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lunova_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lunova_backend.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SECURE = True    # Prod’da HTTPS zorunlu
SESSION_COOKIE_SAMESITE = None  # Cross-site cookie için None
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = None   # Eğer CSRF cookie de kullanacaksan

# Custom header'lara izin ver
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-frontend-type',  # Custom header'ımız
]

USE_X_FORWARDED_HOST = True

# Environment - required
ENVIRONMENT = env.str('ENVIRONMENT')
if not ENVIRONMENT:
    print("ENVIRONMENT variable is missing!")
    raise ImproperlyConfigured("ENVIRONMENT environment variable is required!")

# Frontend URLs - JSON format
FRONTEND_URLS = env.json('FRONTEND_URLS')
if not FRONTEND_URLS:
    print("FRONTEND_URLS variable is missing!")
    raise ImproperlyConfigured("FRONTEND_URLS environment variable is required!")

# CORS ve SESSION ayarları
if env.str('ENVIRONMENT') == 'Production':
    try:
        FRONTEND_URLS = env.json('FRONTEND_URLS')
        # Required roles kontrolü
        required_roles = ['expert', 'client', 'admin']
        for role in required_roles:
            if role not in FRONTEND_URLS:
                print(f"Frontend URL for role '{role}' is missing!")
                raise ImproperlyConfigured(f"Frontend URL for role '{role}' is missing!")
                
        # CORS için tüm frontend URL'lerini al (value'ları)
        CORS_ALLOWED_ORIGINS = list(FRONTEND_URLS.values())
        if not CORS_ALLOWED_ORIGINS:
            print("No frontend URLs found for CORS!")
            raise ImproperlyConfigured("No frontend URLs found for CORS!")
            
    except ValueError as e:
        raise ImproperlyConfigured(f"Invalid FRONTEND_URLS JSON format: {e}")
    SESSION_COOKIE_DOMAIN = ".lunova.tr"
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:5174",
    ]
    # Localde domain ayarı gerekmez
    SESSION_COOKIE_DOMAIN = None

# HTTPS reverse proxy arkasında çalışırken güvenli protokolü algılaması için:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CookieJWTAuthentication',
    ),
}

AUTH_USER_MODEL = 'accounts.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_SAMESITE': 'None',
}

# Email Settings
EMAIL_BACKEND = env.str('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env.str('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', default='noreply@lunova.com')

# Zoom API Settings
ZOOM_CLIENT_ID = env.str('ZOOM_CLIENT_ID')
ZOOM_CLIENT_SECRET = env.str('ZOOM_CLIENT_SECRET')
ZOOM_ACCOUNT_ID = env.str('ZOOM_ACCOUNT_ID')
