# Generated by Django 5.2.4 on 2026-01-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Form Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Form Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('instructions', models.TextField(blank=True, verbose_name='Talimatlar')),
                ('disclaimer', models.TextField(blank=True, verbose_name='Etik Hatırlatma')),
                ('stage', models.PositiveIntegerField(default=1, verbose_name='Aşama')),
                ('max_score', models.FloatField(blank=True, null=True, verbose_name='Maksimum Puan')),
                ('min_score', models.FloatField(blank=True, null=True, verbose_name='Minimum Puan')),
                ('scoring_type', models.CharField(choices=[('none', 'Puanlama Yok'), ('binary', 'Evet/Hayır (0-1)'), ('scale', 'Ölçek (0-4)'), ('weighted', 'Ağırlıklı'), ('custom', 'Özel')], default='none', max_length=20, verbose_name='Puanlama Tipi')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Formlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskLevelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50, verbose_name='Form Tipi')),
                ('min_score', models.FloatField(verbose_name='Minimum Puan')),
                ('max_score', models.FloatField(verbose_name='Maksimum Puan')),
                ('risk_level', models.CharField(max_length=100, verbose_name='Risk Seviyesi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('recommendations', models.TextField(blank=True, verbose_name='Öneriler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Risk Seviyesi Eşleştirmesi',
                'verbose_name_plural': 'Risk Seviyesi Eşleştirmeleri',
                'ordering': ['form_type', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Toplam Puan')),
                ('risk_level', models.CharField(blank=True, max_length=100, verbose_name='Risk Seviyesi')),
                ('percentage_score', models.FloatField(blank=True, null=True, verbose_name='Yüzde Puan')),
                ('interpretation', models.TextField(blank=True, verbose_name='Yorum')),
                ('recommendations', models.TextField(blank=True, verbose_name='Öneriler')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form', verbose_name='Form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Form Cevabı',
                'verbose_name_plural': 'Form Cevapları',
                'ordering': ['-submitted_at'],
                'unique_together': {('form', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('question_type', models.CharField(choices=[('text', 'Açık Uçlu (Text)'), ('yes_no', 'Evet/Hayır'), ('scale', 'Ölçek (0-4)'), ('single_choice', 'Tek Seçim (A/B/C/D)'), ('multiple_choice', 'Çok Seçimli'), ('number', 'Sayısal'), ('date', 'Tarih'), ('textarea', 'Uzun Metin')], max_length=20, verbose_name='Soru Tipi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
                ('score_weight', models.FloatField(default=1.0, verbose_name='Puan Ağırlığı')),
                ('min_scale_value', models.FloatField(default=0.0, verbose_name='Minimum Ölçek Değeri')),
                ('max_scale_value', models.FloatField(default=4.0, verbose_name='Maksimum Ölçek Değeri')),
                ('scale_labels', models.JSONField(blank=True, help_text="Ölçek etiketleri, örn: {'0': 'Hiçbir zaman', '1': 'Nadiren', '2': 'Bazen', '3': 'Sıklıkla', '4': 'Her zaman'}", null=True, verbose_name='Ölçek Etiketleri')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form', verbose_name='Form')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.question', verbose_name='Sonraki Soru')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='Seçenek Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('score_value', models.FloatField(default=0.0, verbose_name='Puan Değeri')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru Cevap mı?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.question', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Soru Seçeneği',
                'verbose_name_plural': 'Soru Seçenekleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Metin Cevabı')),
                ('numeric_answer', models.FloatField(blank=True, null=True, verbose_name='Sayısal Cevap')),
                ('answer_score', models.FloatField(default=0.0, verbose_name='Cevap Puanı')),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formresponse', verbose_name='Form Cevabı')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question', verbose_name='Soru')),
                ('selected_options', models.ManyToManyField(blank=True, to='forms.questionoption', verbose_name='Seçilen Seçenekler')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'unique_together': {('form_response', 'question')},
            },
        ),
    ]
