# Generated by Django 5.2.4 on 2026-08-19 13:48

import uuid
from django.db import migrations, models


def assign_distinct_group_keys(apps, schema_editor):
    """AddField(default=uuid.uuid4) var olan satırlar için callable default'u
    sadece BİR KEZ değerlendirip DDL'e gömer - yani mevcut tüm satırlar
    (rollback edilen ilk deneme bunu kanıtladı: 3 form da AYNI group_key'i
    alıp bir sonraki AddConstraint'te unique ihlaline yol açtı) aynı UUID'yi
    paylaşır. Bu adım her satıra elle, gerçekten benzersiz bir UUID atar."""
    Form = apps.get_model('forms', 'Form')
    for form in Form.objects.all():
        form.group_key = uuid.uuid4()
        form.save(update_fields=['group_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='group_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Aynı formun tüm versiyonlarını birbirine bağlayan sabit kimlik.', verbose_name='Versiyon Grubu'),
        ),
        migrations.AddField(
            model_name='form',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon'),
        ),
        migrations.RunPython(assign_distinct_group_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('group_key', 'version'), name='forms_form_unique_group_version'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group_key',), name='forms_form_one_active_per_group'),
        ),
    ]
